version: '2.2'

services:

  es06:
    image: elasticsearch:7.8.0
    container_name: es06
    environment:
      - node.name=es06
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=es06
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.port=9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge
